Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.ssh.forward_agent = true
  config.vm.provision "shell", path: "provision.sh", privileged: false
  config.vm.provider "virtualbox" do |vb|
    vb.name = "cop3402fall19"
    vb.memory = "4096"
    vb.cpus = "2"
  end
end
